### ISSUE TITLE
Directory not found

### ISSUE THREAD

**Issue by MarliesJFrancine** [estebanpw/chromeister#33]
Hi, when downloading the zip file "chromeister-1.5.a.zip" and unzipping it, I cannot install it by running the given command:

cd chromeister && make all -C src/ && python3 -m venv chromeisterenv && source chromeisterenv/bin/activate && pip install -r src/requirements.txt

There is not directory called "chromeister" in the unzipped file, nor is there an "activate" in the "bin" directory. 

Am I missing something here or doing something wrong?

**Comment by estebanpw** [comment]
Hello! 

If you downloaded the zip (instead of doing a `git clone ...`) then most likely when you unzip the file you have a folder named `chromeister-1.5.a` or something like that. Then you would need to change the command to:

`cd chromeister-1.5.a && make all -C src/ && python3 -m venv chromeisterenv && source chromeisterenv/bin/activate && pip install -r src/requirements.txt`

If that does not work, can you post the contents of the folder in which you extracted the zip?

Have a nice weekend,
Esteban

**Comment by MarliesJFrancine** [comment]
Hi Esteban, 
Thank you for getting back to me! It works now, thanks a lot :)

Kind regards,
Marlies
