### ISSUE TITLE
error of removal of "index-refseq-qryseq.csv" 

### ISSUE THREAD

**Issue by XuewenWangUGA** [estebanpw/chromeister#4]
In addition, there is another small issue where the removal of "index-refseq-qryseq.csv" is not successful, which cause an error.
It seems that that is caused by the directory /path issue.

error information: 
Launching... /home/xuewen/Downloads/chromeister-master/bin/index_chromeister_solo.sh . index-refseq-qryseq.csv /home/xuewen/Downloads/chromeister-master/refseq /home/xuewen/Downloads/chromeister-master/qryseq
rm: cannot remove 'index-refseq-qryseq.csv': No such file or directory

**Comment by estebanpw** [comment]
Dear Xuewen,

I assume you used the script all_vs_all (either the incremental or the other one). Although an error appears when the script launches the index generation (The "Launching .... " command) the output should be OK. This is just a `rm` command that removes the csv file in case it existed already, so that new results dont get appended to old results (i.e. overwrite them).

In the same folder you executed the script there should be a CSV file called "index-folderNameA-folderNameB.csv" with contents that look like this:

**SpX, SpY, IDX, IDY, IMG, CHNumberX, CHNumberY, Score, LengthX, LengthY**
Bos_taurus.X,Homo_sapiens.X,>X dna:chromosome chromosome:UMD3.1:X:1:148823899:1 REF,>X dna:chromosome chromosome:GRCh37:X:1:155270560:1 REF,Bos_taurus.X.fasta-Homo_sapiens.X.fasta.mat.filt.png,NULL,NULL, 0.343,148823899,155270560
Mus_musculus.X,Homo_sapiens.X,>X dna:chromosome chromosome:GRCm38:X:1:171031299:1 REF,>X dna:chromosome chromosome:GRCh37:X:1:155270560:1 REF,Mus_musculus.X.fasta-Homo_sapiens.X.fasta.mat.filt.png,NULL,NULL, 0.482,171031299,155270560

As you can see this is the index of comparing the homo sapiens X chromosome in one folder against another folder containing bos taurus X chromosome and Mus musculus X chromosome. There will be a line in the csv per each comparison containing the names of the sequences, ids, where the .png dotplot is stored, the score (e.g. the 0.343) per comparison and the lengths. The null values are yet to  be used.

Hope it helps,
Esteban
