### ISSUE TITLE
Error in axis - no locations are finite

### ISSUE THREAD

**Issue by Ben7124** [estebanpw/chromeister#7]
Hello, 

I ran Chromeister and I get the following error. Could you please help me? Thanks!

./CHROMEISTER -query query.fa -db ref.fa -out dotplot.mat && Rscript compute_score.R dotplot.mat 1000
[INFO] Generating a 1000x1000 matrix
[INFO] Loading database
100%...[INFO] Database loaded and of length 557480303.
[INFO] Ratios: Q [6.709421e+05] D [5.574803e+05]. Lenghts: Q [670942087] D [557480303]
[INFO] Pixel size: Q [1.490442e-06] D [1.793785e-06].
[INFO] Computing absolute hit numbers.
100%...Scanning hits table.
100%...
[INFO] Query length 670942087.
[INFO] Writing matrix.
[INFO] Found 299180 unique hits for z = 4.
[1] 0.996
Error in axis(1, tick = FALSE, labels = seq_x_labels, at = seq_x_ticks) : 
  no locations are finite
Execution halted

**Comment by estebanpw** [comment]
Dear @Ben7124 

can you please try to run it with the following command:

```./CHROMEISTER -query query.fa -db ref.fa -out dotplot.mat && Rscript compute_score-nogrid.R dotplot.mat 1000```

Notice that instead of the compute_score.R, the no-grid version is used, as it seems there is some problem with the axes.

How many sequences are contained in your fasta inputs? 

Is it possible for you to share your sequences so that I can try to reproduce the error?

PD: Even after we get the plot right, notice that the score for the two sequences is close to 1 (which is no similarity at all for CHROMEISTER, remember that it filters out repeats)

**Comment by estebanpw** [comment]
Dear @Ben7124 
I found out the problem that was causing this. It had to do with the names of the sequences (the headers in the FASTA files). I am pushing a fix for this. Thanks for reporting it!
